# Arrays for Numerical work?



In [1]:
a = [1,2,3]
b = [4,5,6]
c = a+b
print(c)

[1, 2, 3, 4, 5, 6]


You can see, adding two lists just results in a longer list, catenation of the two.


In [2]:
a.append(b)
print(a)

[1, 2, 3, [4, 5, 6]]


In [3]:
def sum(data):
    """ sum the elements of an array
    """
    asum = 0.0
    for i in data:
        asum = asum + i
    return asum

In [4]:
# the length of the array is defined here, and re-used below

n = 10

In [5]:
%%time
a = list(range(n))

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 12.2 µs


In [6]:
%%time
print(sum(a))

45.0
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 44.6 µs


In [7]:
import numpy as np

In [8]:
%%time
a=np.arange(n)


CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 36.5 µs


In [9]:
%%time
print(sum(a))

45.0
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 93 µs


In [10]:
#%%time
%time print(a.sum())
%time print(a.sum())

45
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 3.31 ms
45
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 80.6 µs


In [11]:
a=np.arange(10)
b=np.arange(10)
c = a + b
d = 3*a*a + b + 2.0
print(c)
print(d)

[ 0  2  4  6  8 10 12 14 16 18]
[   2.    6.   16.   32.   54.   82.  116.  156.  202.  254.]


In [12]:
c.shape

(10,)

In [13]:
c2=c.reshape(5,2)
c3=c.reshape(2,5)

In [14]:
print(c)
print(c2)
print(c3)
type(c)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]


numpy.ndarray

In [15]:
c[0]=999

In [16]:
print(c2)

[[999   2]
 [  4   6]
 [  8  10]
 [ 12  14]
 [ 16  18]]


In [17]:
d2=c.reshape(5,2)[1:3,:]

In [18]:
print(d2)

[[ 4  6]
 [ 8 10]]


In [19]:
d2[1,1]=888

In [20]:
print(c)

[999   2   4   6   8 888  12  14  16  18]


In [21]:
print(c2)

[[999   2]
 [  4   6]
 [  8 888]
 [ 12  14]
 [ 16  18]]


Finally, this notebook can also be saved in python, and run through ipython (*or python if no cell_magic was used*). Try this out!

Notice the difference in running it via
```
    python 03-arrays.py
```
and
```
    ipython 03-arrays.py
```
